config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates :name, presence: true
    has_many :vote_logs
    
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from ActiveRecord::RecordNotFound, with: :id_not_found
    def id_not_found
        # render html: "Fail!!!"
        render file:Rails.root.join('public', '404.html'), layout: false, status: 404 and return 
    end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]
  def index
    @candidates = Candidate.all
    if params[:keyword].present?
      @candidates = @candidates.where("name like ?", "%#{params[:keyword]}%").or(@candidates.where("party like ?", "%#{params[:keyword]}%"))
    end
  end
  
  def show
  end
  
  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to '/candidates', notice: "Add new candidate success!"
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @candidate.update(candidate_params)
      redirect_to '/candidates', notice:"Update success!"
    else  
      render :edit
    end
  end
  
  def destroy
    @candidate.destroy
    redirect_to "/candidates", notice: "You destroy the data!"
  end

  def vote
    # VoteLog.create(candidate: @candidate, ip_address: request.remote_ip)
    @candidate.vote_logs.create(ip_address: request.remote_ip)

    redirect_to "/candidates",notice:"You voted."
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :party, :age, :politics)
  end
  def find_candidate
    @candidate = Candidate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if candidate.errors.full_messages %>
  <ul>
    <%  candidate.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for candidate do |form| %>
  <div>
    <%= form.label :name, "名字" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :party, "政黨" %>
    <%= form.text_field :party %>
  </div>
  <div>
    <%= form.label :age, "年齡" %>
    <%= form.number_field :age, min: 1, max: 99 , value:30%>
  </div>
  <div>
    <%= form.label :politics, "政見" %>
    <%= form.text_area :politics %>
  </div>
  <%= form.submit %>
<% end %>

app/views/candidates/edit.html.erb
<h1>Edit</h1>
<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>Candidates Index Html Erb</h1>
<form action="" name="">
  <input type="text" name="keyword" placeholder="關鍵字">
  <input type="submit" value="Search">
</form>
<table>
  <th>
    <td></td>
    <td>Total Votes</td>
    <td>Name:</td>
    <td>Party:</td>
    <td>Age:</td>
    <td>Politics:</td>
    <td>Action:</td>
  </th>
  <% @candidates.each do |candidate| %>
    <tr>
      <td><%= link_to "VOTE", vote_candidate_path(candidate.id), method: "post" %></ td>
      <td><%= candidate.vote_logs.size %></ td>
      <td><%= link_to candidate.name, candidate_path(candidate.id) %></ td>
      <td><%= candidate.party %></td>
      <td><%= candidate.age %></td>
      <td><%= candidate.politics %></td>
      <td><%= link_to "Edit", edit_candidate_path(candidate.id) %></td>
      <td><%= link_to "Delete", candidate_path(candidate.id), method: "delete" , data: {confirm: "Are you sure!?!?!"} %></td>
    </tr>
  <% end %>
</table>
<a href="/candidates/new">Add Candidate</a>

app/views/candidates/new.html.erb
<h1>Add Candidate</h1>
<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<% if @candidate  %>
  <h1><%= @candidate.name %></h1>
  <ul>
    <li>party: <%= @candidate.party  %></li>
    <li>age: <%= @candidate.age %></li>
    <li>politics: <%= @candidate.politics %></li>
  </ul>
<% else %>
  <h1>No record found!</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src= "/app/javascript/candidate_order.js"></script>
  </head>
  <body>
    <%= flash[:notice]  %>
    <%= yield %>
  </body>
</html>